/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HelpCentreRouteImport } from './routes/help-centre'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as BookingReferenceRouteImport } from './routes/booking.$reference'
import { Route as ListingSlugRouteImport } from './routes/listing.$slug'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthOauthRouteImport } from './routes/api/auth/oauth'
import { Route as ApiAuthProfileRouteImport } from './routes/api/auth/profile'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as ApiPublicKeepaliveRouteImport } from './routes/api/public/keepalive'
import { Route as ApiPublicBookingReferenceRouteImport } from './routes/api/public/booking.$reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCentreRoute = HelpCentreRouteImport.update({
  id: '/help-centre',
  path: '/help-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingReferenceRoute = BookingReferenceRouteImport.update({
  id: '/booking/$reference',
  path: '/booking/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingSlugRoute = ListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOauthRoute = ApiAuthOauthRouteImport.update({
  id: '/api/auth/oauth',
  path: '/api/auth/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeepaliveRoute = ApiPublicKeepaliveRouteImport.update({
  id: '/api/public/keepalive',
  path: '/api/public/keepalive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingReferenceRoute =
  ApiPublicBookingReferenceRouteImport.update({
    id: '/api/public/booking/$reference',
    path: '/api/public/booking/$reference',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/help-centre': typeof HelpCentreRoute
  '/planner': typeof PlannerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/oauth': typeof ApiAuthOauthRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/public/keepalive': typeof ApiPublicKeepaliveRoute
  '/api/public/booking/$reference': typeof ApiPublicBookingReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/help-centre': typeof HelpCentreRoute
  '/planner': typeof PlannerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/oauth': typeof ApiAuthOauthRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/public/keepalive': typeof ApiPublicKeepaliveRoute
  '/api/public/booking/$reference': typeof ApiPublicBookingReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/help-centre': typeof HelpCentreRoute
  '/planner': typeof PlannerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/booking/$reference': typeof BookingReferenceRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/oauth': typeof ApiAuthOauthRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/public/keepalive': typeof ApiPublicKeepaliveRoute
  '/api/public/booking/$reference': typeof ApiPublicBookingReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cancellation-policy'
    | '/dashboard'
    | '/explore'
    | '/help-centre'
    | '/planner'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/booking/$reference'
    | '/listing/$slug'
    | '/api/auth/me'
    | '/api/auth/oauth'
    | '/api/auth/profile'
    | '/api/auth/register'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/public/keepalive'
    | '/api/public/booking/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cancellation-policy'
    | '/dashboard'
    | '/explore'
    | '/help-centre'
    | '/planner'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/booking/$reference'
    | '/listing/$slug'
    | '/api/auth/me'
    | '/api/auth/oauth'
    | '/api/auth/profile'
    | '/api/auth/register'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/public/keepalive'
    | '/api/public/booking/$reference'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cancellation-policy'
    | '/dashboard'
    | '/explore'
    | '/help-centre'
    | '/planner'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/booking/$reference'
    | '/listing/$slug'
    | '/api/auth/me'
    | '/api/auth/oauth'
    | '/api/auth/profile'
    | '/api/auth/register'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/api/public/keepalive'
    | '/api/public/booking/$reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  HelpCentreRoute: typeof HelpCentreRoute
  PlannerRoute: typeof PlannerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  BookingReferenceRoute: typeof BookingReferenceRoute
  ListingSlugRoute: typeof ListingSlugRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthOauthRoute: typeof ApiAuthOauthRoute
  ApiAuthProfileRoute: typeof ApiAuthProfileRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiPublicKeepaliveRoute: typeof ApiPublicKeepaliveRoute
  ApiPublicBookingReferenceRoute: typeof ApiPublicBookingReferenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-centre': {
      id: '/help-centre'
      path: '/help-centre'
      fullPath: '/help-centre'
      preLoaderRoute: typeof HelpCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$reference': {
      id: '/booking/$reference'
      path: '/booking/$reference'
      fullPath: '/booking/$reference'
      preLoaderRoute: typeof BookingReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$slug': {
      id: '/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/listing/$slug'
      preLoaderRoute: typeof ListingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/oauth': {
      id: '/api/auth/oauth'
      path: '/api/auth/oauth'
      fullPath: '/api/auth/oauth'
      preLoaderRoute: typeof ApiAuthOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keepalive': {
      id: '/api/public/keepalive'
      path: '/api/public/keepalive'
      fullPath: '/api/public/keepalive'
      preLoaderRoute: typeof ApiPublicKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking/$reference': {
      id: '/api/public/booking/$reference'
      path: '/api/public/booking/$reference'
      fullPath: '/api/public/booking/$reference'
      preLoaderRoute: typeof ApiPublicBookingReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  HelpCentreRoute: HelpCentreRoute,
  PlannerRoute: PlannerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  BookingReferenceRoute: BookingReferenceRoute,
  ListingSlugRoute: ListingSlugRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthOauthRoute: ApiAuthOauthRoute,
  ApiAuthProfileRoute: ApiAuthProfileRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiPublicKeepaliveRoute: ApiPublicKeepaliveRoute,
  ApiPublicBookingReferenceRoute: ApiPublicBookingReferenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
